name: fab22
channels:
    - conda-forge

dependencies:
   - python=3.8
   - pip
   - git
   - compas=1.16
   - compas_fab=0.26
   - compas_cgal=0.4
   - compas_rrc=1.1
   - pip:
     - ur-rtde==1.5.1
